### ISSUE TITLE
allow movements that stick after the end of the command

### ISSUE THREAD

**Issue by aoloe** [gu-fan/autotype.vim#1]
would it be easy to optionally allow the movements to stick after the command?

that would be amazing!

**Comment by aoloe** [comment]
ok, nevermind... i've found

`:let g:autotype_moveback = 0`

by browsing the source code... and once i've found it there, i also found it in the README... you might want to link to that line at the place where it say that the default behavior is to go back to the end of the document...

**Comment by gu-fan** [comment]
haha 👍
